OAuth2Server\Entities\UserEntity:
  type: entity
  table: oauth_users
  repositoryClass:  OAuth2Server\Repositories\UserRepository
  id:
    id:
      type:   integer
      generator:
        strategy: AUTO
  fields:
    email:
      type:   string
      unique: true
    password:
      type:   string
  indexes:
    email_index:
      columns: [ email ]
