OAuth2Server\Entities\AccessTokenEntity:
  type:             entity
  table:            oauth_access_tokens
  repositoryClass:  OAuth2Server\Repositories\AccessTokenRepository
  id:
    id:
      type:   integer
      generator:
        strategy: AUTO
  fields:
    token:
      type:       string
      max_length: 40
      unique:     true
    client_id:
      type:       integer
    user_id:
      type:       integer
      nullable:   true
    expires:
      type:       datetime
    scope:
      type:       string
      max_length: 50
      nullable:   true
  manyToOne:
    client:
      targetEntity: OAuth2Server\Entities\ClientEntity
      joinColumn:
        name:                 client_id
        referencedColumnName: id
    user:
      targetEntity: OAuth2Server\Entities\UserEntity
      joinColumn:
        name:                 user_id
        referencedColumnName: id
