OAuth2Server\Entities\ClientEntity:
  type:             entity
  table:            oauth_clients
  repositoryClass:  OAuth2Server\Repositories\ClientRepository
  id:
    id:
      type:   integer
      generator:
        strategy: AUTO
  fields:
    client_identifier:
      type:       string
      max_length: 50
      unique:     true
    client_secret:
      type:       string
      max_length: 20
    redirect_uri:
      type:       string
      max_length: 255
      default:    ""
